CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'identity') THEN
        CREATE SCHEMA identity;
    END IF;
END $EF$;

CREATE TABLE identity."Invites" (
    "Id" uuid NOT NULL,
    "GuestEmail" text NOT NULL,
    "GuestRole" integer NOT NULL,
    "InvitedAt" timestamp with time zone NOT NULL,
    "AcceptedAt" timestamp with time zone,
    "UserId" integer,
    "CondominiumId" integer NOT NULL,
    CONSTRAINT "PK_Invites" PRIMARY KEY ("Id")
);

CREATE TABLE identity."Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ExternalId" uuid NOT NULL,
    "Email" text NOT NULL,
    "FullName" text NOT NULL,
    "AvatarUrl" text,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE identity."CondominiumMemberships" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Role" integer NOT NULL,
    "JoinDate" timestamp with time zone NOT NULL,
    "CondominiumId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_CondominiumMemberships" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CondominiumMemberships_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CondominiumMemberships_UserId" ON identity."CondominiumMemberships" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260129210915_Identity_User_Invite_Membership', '10.0.0');

COMMIT;

