// <auto-generated />
using System.Collections.Generic;
using Condominiums.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Condominiums.Infrastructure.Migrations
{
    [DbContext(typeof(CondominiumDbContext))]
    [Migration("20260407202628_resident_prospect_case_insensitive_indexes")]
    partial class resident_prospect_case_insensitive_indexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("condominium")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Condominiums.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IbgeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.HasIndex(new[] { "IbgeCode" }, "Index_Cities_IbgeCode")
                        .IsUnique();

                    b.ToTable("Cities", "condominium");
                });

            modelBuilder.Entity("Condominiums.Domain.Entities.Condominium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "Condominiums.Domain.Entities.Condominium.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CityId")
                                .HasColumnType("integer");

                            b1.Property<string>("Complement")
                                .HasColumnType("text");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.ToTable("Condominiums", "condominium");
                });

            modelBuilder.Entity("Condominiums.Domain.Entities.ResidentProspect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apartment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("citext");

                    b.Property<string>("Block")
                        .HasMaxLength(50)
                        .HasColumnType("citext");

                    b.Property<int>("CondominiumId")
                        .HasColumnType("integer");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId", "Apartment")
                        .IsUnique()
                        .HasDatabaseName("UX_ResidentProspects_CondominiumId_Apartment_WithoutBlock")
                        .HasFilter("\"Block\" IS NULL");

                    b.HasIndex("CondominiumId", "Cpf")
                        .IsUnique()
                        .HasDatabaseName("UX_ResidentProspects_CondominiumId_Cpf");

                    b.HasIndex("CondominiumId", "Apartment", "Block")
                        .IsUnique()
                        .HasDatabaseName("UX_ResidentProspects_CondominiumId_Apartment_Block_WithBlock")
                        .HasFilter("\"Block\" IS NOT NULL");

                    b.ToTable("ResidentProspects", "condominium");
                });

            modelBuilder.Entity("Condominiums.Domain.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("States", "condominium");
                });

            modelBuilder.Entity("Condominiums.Domain.Entities.Tower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentsPerFloor")
                        .HasColumnType("integer");

                    b.Property<int>("CondominiumId")
                        .HasColumnType("integer");

                    b.Property<int>("FloorCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.ToTable("Towers", "condominium");
                });

            modelBuilder.Entity("Condominiums.Domain.Entities.City", b =>
                {
                    b.HasOne("Condominiums.Domain.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Condominiums.Domain.Entities.ResidentProspect", b =>
                {
                    b.HasOne("Condominiums.Domain.Entities.Condominium", "Condominium")
                        .WithMany("ResidentProspects")
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominium");
                });

            modelBuilder.Entity("Condominiums.Domain.Entities.Tower", b =>
                {
                    b.HasOne("Condominiums.Domain.Entities.Condominium", "Condominium")
                        .WithMany("Towers")
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominium");
                });

            modelBuilder.Entity("Condominiums.Domain.Entities.Condominium", b =>
                {
                    b.Navigation("ResidentProspects");

                    b.Navigation("Towers");
                });

            modelBuilder.Entity("Condominiums.Domain.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
